language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsboasorte
  api_key:
    secure: m4hexco5nIByTBpfRtpUBRqJy6wJNtmtgwO8ExHbRIpZK+7IGwFgSG9o8TE9haowsnHwKPfqicnrsDVFOq1t2vdk9LLB48Nc2gzq7GXI7yVX005WBlAcOZySHF/Pcz49murWQjdRaSfp7e6aw6mpZ3PQDvTzgd7hNIalVYiEF5wu+BxmOB9LOkbfSRDqvPiEflUVUcLj1UXtpSqi/H6bzwXqVtOxNbGUXgc+/fxLXykLzYJYVuLYjHnb3FBtw+Tpf0MtEDBMFDDxLhMmlhjewTZVJEPGIdgnRG7cI2UQL3MAeY27iH2Juu2vAsEDBga6A6BSqxllXUGEuoh0eFOCIr3bnwpQZuA0OV1YwKmwvOXvJHMJW0ou+EWCe6dOAPVDbEkY9GI697a8zFbxOX0B63iyqhBdwln3apEPiY4lqdQbMvOEZxN6fgK2vbCEIOEaaXv5PXGM+zqTKeM9bYTiuQdNo88bxyzPQZa1r3py+tpcil2GobyOATBGs7RvwAPOkZpgCWtRkALlQLT1k0nrT/O+Q52hgoXO11tIj2c5Zy/8lNYyeDZtd4srH5baw7LGajuvkANcPBC/lfHDYoT8UoWA6D81oJubVT7EJpQot1e7EhKtHeECMaU3m3+xWoh8DBhuizunaxzgHNY4orIkOEAQR1WNkTTSLYnLQ+TE1IY=
